In [1]:
import numpy as np

In [3]:
List_1=[10,20,30,40]
List_1

[10, 20, 30, 40]

In [4]:
type(List_1)

list

In [8]:
Tuple_1 = (10,20,30,40)


In [9]:
type(Tuple_1)

tuple

In [10]:
Tuple_1[1]=50

TypeError: 'tuple' object does not support item assignment

convert list to array entity

In [11]:
arr = np.array(List_1)

In [12]:
arr

array([10, 20, 30, 40])

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr[2]

np.int64(30)

In [16]:
arr[1:3]

array([20, 30])

In [19]:
#Arrange
np.arange(10,80,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [23]:
np.linspace(10,80,5)

array([10. , 27.5, 45. , 62.5, 80. ])

In [25]:
np.random.randint(20,100,15)

array([34, 98, 37, 27, 45, 49, 47, 37, 27, 24, 92, 41, 73, 64, 48])

In [29]:
arr_rand=np.random.randint(20,100,16)
arr_rand

array([84, 97, 91, 68, 98, 65, 61, 60, 94, 87, 28, 64, 59, 99, 67, 79])

In [31]:
arr_rand_2d= arr_rand.reshape(4,4)
arr_rand_2d

array([[84, 97, 91, 68],
       [98, 65, 61, 60],
       [94, 87, 28, 64],
       [59, 99, 67, 79]])

In [34]:
arr_rand_2d[0:3,2:]

array([[91, 68],
       [61, 60],
       [28, 64]])

Conditional operations

In [37]:
arr1=np.random.randint(20,500,16)
arr1

array([186, 103, 390, 355, 409,  41, 476, 298, 322, 343,  55, 221, 424,
       308, 323, 245])

In [38]:
arr1[(arr1<100) & (arr1>50)]

array([55])

In [39]:
arrA= np.array([22,33,44,55])
arrB= np.array([25,35,45,60])

In [41]:
arrA*arrB

array([ 550, 1155, 1980, 3300])

In [42]:
np.sqrt(arrA)

array([4.69041576, 5.74456265, 6.63324958, 7.41619849])

In [43]:
np.sin(arrA)

array([-0.00885131,  0.99991186,  0.01770193, -0.99975517])

In [44]:
np.max(arrA)

np.int64(55)

In [45]:
np.min(arrA)

np.int64(22)

In [46]:
np.argmin(arrA)

np.int64(0)

In [47]:
np.argmax(arrA)

np.int64(3)