In [1]:
import numpy as np

In [2]:
mass=[12,20,25]

In [3]:
mass_array = np.array(mass)

In [5]:
for mass in mass_array:
    weight= mass * 9.8
    print(weight)

117.60000000000001
196.0
245.00000000000003


**<center>Looping over a 2D numpy array</center>**

In [6]:
# create 2D numpy array using list of lists
massvolume = [[12,20,25],[36,18,10]]

In [7]:
massvolume_array = np.array(massvolume)

In [9]:
for value in massvolume_array:
    print (value)

[12 20 25]
[36 18 10]


In [10]:
# Use nditer function to loop

for value in np.nditer(massvolume_array):
    print(value)

12
20
25
36
18
10


In [12]:
#Take 1st row only
for value in np.nditer(massvolume_array[0]):
    weight = value * 9.8
    print(weight)


117.60000000000001
196.0
245.00000000000003


In [14]:
my_2d_array = np.arange(15).reshape(3,5)
my_2d_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
new_array = my_2d_array[2:4]
new_array

array([[10, 11, 12, 13, 14]])